name: Build

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  proton:
    name: ${{ inputs.name }}
    runs-on: ubuntu-latest
    steps:
    - name: Prepare host
      run: sudo apt update && sudo apt-get install -y ccache fontforge-nox

    - name: Download cache
      uses: actions/cache@v3
      with:
        path: ~/.ccache
        key: ccache-proton-${{ github.run_id }}
        restore-keys: |
          ccache-proton

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: recursive

    - name: Patch
      run: |
        # strip binaries at compile time to save space in the runner
        patch -Np1 -i ./.github/patches/0001-strip-binaries-early.patch
        # apply proton-ge-custom patches
        ./patches/protonprep-valve-staging.sh || true
        mkdir ./build

    - name: Configure
      working-directory: ./build
      run: ../configure.sh --build-name=${{ inputs.name }} --container-engine=docker

    - name: Make ${{ inputs.name }}
      working-directory: ./build
      run: make -j3 redist

    - name: Upload artifact ${{ inputs.name }}.tar.gz
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}.tar.gz
        path: ./build/${{ inputs.name }}.tar.gz

    - name: Upload artifact ${{ inputs.name }}.sha512sum
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}.sha512sum
        path: ./build/${{ inputs.name }}.sha512sum
